### ISSUE TITLE
at 100% of cpu

### ISSUE THREAD

**Issue by dtaht** [jech/shncpd#2]
I took shcncpd for a spin yesterday, finding the basic functionality working, only to find this morning
that it was eating 100% of cpu. It is not making a lot of syscalls, one of these goes by every few seconds, but that is certainly not enough to explain the cpu usage. I will try to fire it up again in a debugger to see if I can make it happen again.

sendto(3, "\0\3\0\10\231\212a\370\0\0\0\3\0\4\0\10R\242i\377]{\202\31", 24, 0, {sa_family=AF_INET6, sin6_port=htons(8808), inet_pton(AF_INET6, "ff02::8808", &sin6_addr), sin6_flowinfo=0, sin6_scope_id=if_nametoindex("wlp2s0")}, 28) = 24
socket(PF_LOCAL, SOCK_DGRAM|SOCK_CLOEXEC, 0) = 4
ioctl(4, SIOCGIFINDEX, {ifr_name="wlp2s0", ifr_index=3}) = 0
close(4)                                = 0
open("/proc/sys/net/ipv6/conf/all/forwarding", O_RDONLY) = 4
read(4, "1\n", 99)                      = 2
close(4)                                = 0
rt_sigaction(SIGINT, {SIG_IGN, [], SA_RESTORER, 0x7f2364a6d2f0}, {0x402b16, [], SA_RESTORER, 0x7f2364a6d2f0}, 8) = 0
rt_sigaction(SIGQUIT, {SIG_IGN, [], SA_RESTORER, 0x7f2364a6d2f0}, {SIG_DFL, [], SA_RESTORER, 0x7f2364a6d2f0}, 8) = 0
rt_sigprocmask(SIG_BLOCK, [CHLD], [], 8) = 0
clone(child_stack=0, flags=CLONE_PARENT_SETTID|SIGCHLD, parent_tidptr=0x7ffcf738a3ac) = 9824
wait4(9824, [{WIFEXITED(s) && WEXITSTATUS(s) == 0}], 0, NULL) = 9824
rt_sigaction(SIGINT, {0x402b16, [], SA_RESTORER, 0x7f2364a6d2f0}, NULL, 8) = 0
rt_sigaction(SIGQUIT, {SIG_DFL, [], SA_RESTORER, 0x7f2364a6d2f0}, NULL, 8) = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=9824, si_status=0, si_utime=0, si_stime=0} ---

It is configured on this x86 box as:

d         3632 99.2  0.0   6540  1668 pts/30   R    Apr11 806:29 shncpd -D -M wlp2s0
root      3655  0.0  0.0   6540  1940 pts/30   S    Apr11   0:02 shncpd -D -M wlp2s0

Elsewhere I have it configured to serve addresses - and it is behaving normally. This is on a pi2:

root      3424  0.0  0.1   1984  1340 ?        S    04:01   0:08 shncpd -E fd10::/48 -E 172.26.192.0/20 eth0 wlan0
root      3696  0.0  0.1   1984  1360 ?        S    04:05   0:09 shncpd -D -E fd10::/48 -E 172.26.192.0/20 -M wlan0 eth0

**Comment by jech** [comment]
That's not a trace of shncpd -- it looks like babeld to me.

**Comment by jech** [comment]
Please reopen when you can give more info.
